//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deti()
        {
            this.Zanyatiya = new HashSet<Zanyatiya>();
        }
    
        public int Id_dati { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Phone_roditelya { get; set; }
        public int Id_gruppa { get; set; }
    
        public virtual Gryppa Gryppa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zanyatiya> Zanyatiya { get; set; }
    }
}
