//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindergarten1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSADEntities : DbContext
    {
        public DSADEntities()
            : base("name=DSADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deti> Deti { get; set; }
        public virtual DbSet<Gryppa> Gryppa { get; set; }
        public virtual DbSet<krygok> krygok { get; set; }
        public virtual DbSet<meropriyatie> meropriyatie { get; set; }
        public virtual DbSet<raspisanie> raspisanie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<Zanyatiya> Zanyatiya { get; set; }
    }
}
